### ISSUE TITLE
CSSReloader crashes when using bs-systemjs-hot-reloader in es6 gulp browsersync

### ISSUE THREAD

**Issue by LyraelRayne** [sormy/bs-systemjs-hot-reloader#1]
I'm trying to use bs-systemjs-hot-reloader with CssReloader enabled in a gulp task, however I get the following error when browsersync inits the plugins:

    /Users/testuser/demoapp/jspm_packages/system.js:4615
          $__curScript = typeof __filename != 'undefined' ? { src: __filename } : null;
                   ^

    ReferenceError: $__curScript is not defined
        at /Users/testuser/demoapp/jspm_packages/system.js:5144:3
        at Object.<anonymous> (/Users/testuser/demoapp/jspm_packages/system.js:4:1)
        at Module._compile (module.js:571:32)
        at loader (/Users/testuser/demoapp/node_modules/babel-register/lib/node.js:144:5)
        at Object.require.extensions.(anonymous function) [as .js]     (/Users/testuser/demoapp/node_modules/babel-register/lib/node.js:154:7)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)

The gulpfile.babel.js (using an ES6 gulpfile) is

    import gulp from "gulp";
    import browserSync from "browser-sync";
    import bsSystemHotReloader from "bs-systemjs-hot-reloader";

    gulp.task("server", ["less"], () =>
    {
        var bs = browserSync.create();

    bs.watch([
        'test.html',
        'jspm.config.js'
    ]).on('change', bs.reload);

    bs.use(bsSystemHotReloader, {
        files: [
            'src/**/*.css',
            'src/**/*.js',
            'src/**/*.html',
        ], cssReloader: {
            jspmConfigFile: "jspmconfig/jspm.config.js",
        }
    });

    bs.init({
        online: false,
        open: false,
        reloadOnRestart: true,
        proxy: "https://localhost:9012",
        logLevel: "debug",
        serveStatic: ["."],
    });
    });`

**Comment by sormy** [comment]
what systemjs version do you have?

**Comment by sormy** [comment]
It looks like error comes from SystemJS, it could be related to jspm.config.js placed not in default location.

**Comment by LyraelRayne** [comment]
Hi,

I haven't used systemjs in ages (moved to angular-cli with webpack) and I don't think I have the project anymore where I was playing with this so I can't provide any more details.  Feel free to close this unless you wish to investigate it further.
